### ISSUE TITLE
Can't configure values in nginx-nr-agent.ini.j2

### ISSUE THREAD

**Issue by timorunge** [krzyzakp/ansible-nginx-nr-agent#1]
Per default the log level is set to `level=DEBUG` which can't be changed by either replacing the nginx-nr-agent.ini.j2 or setting variables to change the level via yml files.

Are you planning to implement this? :)

**Comment by krzyzakp** [comment]
@timorunge change implemented, now you can set log level as configure different log levels for each of handlers. By default they're set to same value as for now - `DEBUG`.
